package repository_test

// A pure unit test: no database, no fixtures, just a temp directory. What it pins is
// the boundary that would actually do the damage — the last step between a name and
// an open() call.

import (
	"bytes"
	"context"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"Arthafreestyle/ERP/internal/repository"
)

func storageSementara(t *testing.T) (*repository.LocalDokumenStorage, string) {
	t.Helper()

	root := t.TempDir()

	storage, err := repository.NewLocalDokumenStorage(root)
	if err != nil {
		t.Fatalf("new storage: %v", err)
	}

	return storage, root
}

// Names are generated by the server, so none of these should ever arrive. They are
// refused anyway, because "should never arrive" is exactly the assumption that stops
// holding the day somebody adds a shortcut that reuses the client's filename — and
// the cost of being wrong here is the whole filesystem.
//
// Note what is not done: sanitising. filepath.Base would turn "../../etc/passwd"
// into "passwd" and carry on, converting an attack into a silent write to the wrong
// place. Rejecting says so out loud.
func TestStorageMenolakNamaYangBukanNamaBerkasPolos(t *testing.T) {
	storage, root := storageSementara(t)

	for _, nama := range []string{
		"",
		".",
		"..",
		"../keluar.png",
		"../../config.json",
		"sub/berkas.png",
		`sub\berkas.png`,
		"/etc/passwd",
		`C:\Windows\system32\config`,
	} {
		if _, err := storage.Tulis(context.Background(), nama, strings.NewReader("x")); !errors.Is(err, repository.ErrNamaBerkasTidakSah) {
			t.Errorf("Tulis(%q) error = %v, want ErrNamaBerkasTidakSah", nama, err)
		}

		if _, err := storage.Buka(context.Background(), nama); !errors.Is(err, repository.ErrNamaBerkasTidakSah) {
			t.Errorf("Buka(%q) error = %v, want ErrNamaBerkasTidakSah", nama, err)
		}

		if err := storage.Hapus(context.Background(), nama); !errors.Is(err, repository.ErrNamaBerkasTidakSah) {
			t.Errorf("Hapus(%q) error = %v, want ErrNamaBerkasTidakSah", nama, err)
		}
	}

	entries, err := os.ReadDir(root)
	if err != nil {
		t.Fatalf("read root: %v", err)
	}

	if len(entries) != 0 {
		t.Errorf("storage root is not empty after rejected names: %v", entries)
	}
}

func TestStorageMenulisMembacaDanMenghapus(t *testing.T) {
	storage, root := storageSementara(t)
	isi := bytes.Repeat([]byte("faktur"), 100)

	written, err := storage.Tulis(context.Background(), "berkas.png", bytes.NewReader(isi))
	if err != nil {
		t.Fatalf("tulis: %v", err)
	}

	if written != int64(len(isi)) {
		t.Errorf("written = %d, want %d", written, len(isi))
	}

	if _, err := os.Stat(filepath.Join(root, "berkas.png")); err != nil {
		t.Fatalf("stat stored file: %v", err)
	}

	berkas, err := storage.Buka(context.Background(), "berkas.png")
	if err != nil {
		t.Fatalf("buka: %v", err)
	}

	kembali, err := io.ReadAll(berkas)
	_ = berkas.Close()

	if err != nil {
		t.Fatalf("read: %v", err)
	}

	if !bytes.Equal(kembali, isi) {
		t.Errorf("content changed in storage")
	}

	if err := storage.Hapus(context.Background(), "berkas.png"); err != nil {
		t.Fatalf("hapus: %v", err)
	}

	if _, err := storage.Buka(context.Background(), "berkas.png"); !errors.Is(err, repository.ErrBerkasTidakAda) {
		t.Errorf("Buka after delete = %v, want ErrBerkasTidakAda", err)
	}
}

// Overwriting would mean one attachment silently replacing another's bytes while
// both rows still claim to have their own.
func TestStorageMenolakMenimpaBerkasYangSudahAda(t *testing.T) {
	storage, _ := storageSementara(t)

	if _, err := storage.Tulis(context.Background(), "berkas.png", strings.NewReader("pertama")); err != nil {
		t.Fatalf("tulis pertama: %v", err)
	}

	if _, err := storage.Tulis(context.Background(), "berkas.png", strings.NewReader("kedua")); err == nil {
		t.Fatal("Tulis over an existing name succeeded, want an error")
	}

	berkas, err := storage.Buka(context.Background(), "berkas.png")
	if err != nil {
		t.Fatalf("buka: %v", err)
	}
	defer func() {
		_ = berkas.Close()
	}()

	isi, err := io.ReadAll(berkas)
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	if string(isi) != "pertama" {
		t.Errorf("content = %q, want the original untouched", isi)
	}
}

// The cleanup job may die between deleting a file and marking its row, and the next
// run has to be able to finish the job rather than jam on a file that is already
// gone.
func TestStorageHapusBerkasYangTidakAdaBukanGalat(t *testing.T) {
	storage, _ := storageSementara(t)

	if err := storage.Hapus(context.Background(), "tidak-ada.png"); err != nil {
		t.Errorf("Hapus on a missing file = %v, want nil", err)
	}
}

// A failed write must not leave a partial file: it would have no row pointing at it,
// and the cleanup job works from rows — so nothing would ever find it again.
func TestStorageTidakMeninggalkanBerkasSaatPenulisanGagal(t *testing.T) {
	storage, root := storageSementara(t)

	rusak := io.MultiReader(strings.NewReader("awal"), errorReader{})

	if _, err := storage.Tulis(context.Background(), "berkas.png", rusak); err == nil {
		t.Fatal("Tulis with a failing reader succeeded, want an error")
	}

	entries, err := os.ReadDir(root)
	if err != nil {
		t.Fatalf("read root: %v", err)
	}

	if len(entries) != 0 {
		t.Errorf("storage root = %v, want empty after a failed write", entries)
	}
}

type errorReader struct{}

func (errorReader) Read([]byte) (int, error) { return 0, errors.New("pembacaan gagal") }
