package repository

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// DokumenStorage is where an attachment's bytes live. It sits in the repository
// layer for the same reason SQL does: it is access to a store outside the process,
// and the usecase must not know which one.
//
// The local-disk implementation below is what the project runs today. Swapping it
// for S3 or MinIO means writing another implementation of this interface and
// changing one line in config.Bootstrap — no usecase, controller, or test touches
// the filesystem directly.
//
// Deliberately narrow. No listing, no stat, no rename: the table is the index of
// what exists, and the cleanup job works from rows rather than from a directory
// scan. An implementation that could enumerate its own contents would invite
// exactly the directory-scanning cleanup that deletes files whose row has not been
// committed yet.
type DokumenStorage interface {
	// Tulis writes a new file under nama and reports how many bytes it took. It
	// refuses to overwrite: a name that already exists is an error, never a silent
	// replacement of somebody else's attachment.
	//
	// The caller owns the reader's policy — size limits and checksums are applied by
	// wrapping the reader before it gets here, so this stays a byte pipe.
	Tulis(ctx context.Context, nama string, r io.Reader) (int64, error)

	// Buka opens a stored file for reading. The caller closes it.
	Buka(ctx context.Context, nama string) (io.ReadCloser, error)

	// Hapus removes a stored file. A file that is already gone is not an error: the
	// cleanup job may have died between deleting the file and marking its row, and
	// the retry has to be able to finish the job rather than jam on it.
	Hapus(ctx context.Context, nama string) error
}

// ErrNamaBerkasTidakSah reports a storage name that is not a bare filename.
//
// Names are generated by the server (a UUID plus an extension), so this should be
// unreachable. It is checked anyway, at the boundary that would actually do the
// damage: this is the last line between a name and an open() call, and the whole
// point of never letting the client's filename through is that a path separator
// here turns a storage root into the entire disk.
var ErrNamaBerkasTidakSah = errors.New("nama berkas simpan tidak sah")

// ErrBerkasTidakAda reports a row whose file is missing from storage.
//
// It means the two halves have drifted apart — normally impossible, since a file is
// written before its row and deleted only after the row says so. Kept distinct so a
// usecase can say something honest instead of returning empty bytes with a 200.
var ErrBerkasTidakAda = errors.New("berkas tidak ada di penyimpanan")

// LocalDokumenStorage keeps attachments as files under one directory.
//
// That directory must sit outside anything served as static content and must never
// be executable: the files are supplied by users, and an HTML or SVG among them
// that the application's own origin will render is a stored cross-site scripting
// bug. Nothing in this process serves the directory — downloads go through
// GET /api/v1/dokumen/{id}, which sets Content-Disposition: attachment.
//
// One instance of the application only. Two `web` containers with their own volumes
// each hold half the attachments and answer 404 for the other half; that is the
// price of not adding an object store yet, and it is why the interface above exists.
type LocalDokumenStorage struct {
	root string
}

// NewLocalDokumenStorage creates the storage directory if it is absent and fails if
// it cannot be written to.
//
// Failing here is the point: the alternative is a server that boots happily and
// rejects the first upload of the day, at the receiving desk, with a 500.
func NewLocalDokumenStorage(root string) (*LocalDokumenStorage, error) {
	if strings.TrimSpace(root) == "" {
		return nil, errors.New("dokumen: storage path is empty")
	}

	absolute, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("dokumen: resolve storage path: %w", err)
	}

	// 0o700: attachments carry purchase prices and supplier identities, and nothing
	// outside this process has any business reading them.
	if err := os.MkdirAll(absolute, 0o700); err != nil {
		return nil, fmt.Errorf("dokumen: create storage path: %w", err)
	}

	// MkdirAll succeeds on a directory that exists but is not writable — a bind mount
	// owned by root under a container running unprivileged is the usual way that
	// happens. Prove it is writable now rather than at the first upload.
	probe, err := os.CreateTemp(absolute, ".probe-*")
	if err != nil {
		return nil, fmt.Errorf("dokumen: storage path is not writable: %w", err)
	}

	name := probe.Name()
	_ = probe.Close()
	_ = os.Remove(name)

	return &LocalDokumenStorage{root: absolute}, nil
}

func (s *LocalDokumenStorage) Tulis(ctx context.Context, nama string, r io.Reader) (int64, error) {
	path, err := s.path(nama)
	if err != nil {
		return 0, err
	}

	// O_EXCL, not a plain create: a name that already exists means either a UUID
	// collision or a bug, and both are better as an error than as one attachment
	// silently overwriting another.
	//
	// 0o600 for the same reason the directory is 0o700.
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return 0, fmt.Errorf("dokumen: create file: %w", err)
	}

	written, err := io.Copy(file, r)
	if err != nil {
		_ = file.Close()
		// A half-written file with no row pointing at it is invisible to the cleanup
		// job, which works from rows — so it would sit there forever.
		_ = os.Remove(path)

		return 0, fmt.Errorf("dokumen: write file: %w", err)
	}

	// Sync before the row is written. Without it the row can be committed while the
	// bytes are still only in the page cache, and a crash in between leaves a row
	// pointing at a file that never fully existed.
	if err := file.Sync(); err != nil {
		_ = file.Close()
		_ = os.Remove(path)

		return 0, fmt.Errorf("dokumen: sync file: %w", err)
	}

	if err := file.Close(); err != nil {
		_ = os.Remove(path)

		return 0, fmt.Errorf("dokumen: close file: %w", err)
	}

	return written, nil
}

func (s *LocalDokumenStorage) Buka(ctx context.Context, nama string) (io.ReadCloser, error) {
	path, err := s.path(nama)
	if err != nil {
		return nil, err
	}

	file, err := os.Open(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, ErrBerkasTidakAda
	}
	if err != nil {
		return nil, fmt.Errorf("dokumen: open file: %w", err)
	}

	return file, nil
}

func (s *LocalDokumenStorage) Hapus(ctx context.Context, nama string) error {
	path, err := s.path(nama)
	if err != nil {
		return err
	}

	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("dokumen: remove file: %w", err)
	}

	return nil
}

// path joins nama onto the storage root, refusing anything that is not a bare
// filename.
//
// filepath.Base is not used to sanitise — it would quietly turn "../../etc/passwd"
// into "passwd" and carry on, which is a bug that never announces itself. The name
// is compared against its own Base instead, so anything carrying a directory is
// rejected outright.
//
// Backslash is checked explicitly on top of that: on Linux it is an ordinary
// character in a filename and Base leaves it alone, so a name crafted on one
// platform must not become a path on another.
func (s *LocalDokumenStorage) path(nama string) (string, error) {
	if nama == "" || nama != filepath.Base(nama) ||
		strings.ContainsAny(nama, `/\`) || nama == "." || nama == ".." {
		return "", ErrNamaBerkasTidakSah
	}

	return filepath.Join(s.root, nama), nil
}

var _ DokumenStorage = (*LocalDokumenStorage)(nil)
