-- Siklus penjualan, retur penjualan, dan penerimaan pembayaran.
--
-- Tidak ada termin dan jatuh tempo: pembayaran datang sesuai ketersediaan
-- anggaran pelanggan, bukan tanggal yang disepakati. Penggantinya laporan umur
-- piutang yang dihitung dari penjualan.tanggal.
CREATE TABLE penjualan (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor             VARCHAR        NOT NULL,
    tanggal           TIMESTAMPTZ    NOT NULL,
    id_ruang          BIGINT         NOT NULL,
    id_pelanggan      BIGINT,
    subtotal          NUMERIC(20, 2) NOT NULL DEFAULT 0,
    diskon_nota       NUMERIC(20, 2) NOT NULL DEFAULT 0,
    pembulatan        NUMERIC(20, 2) NOT NULL DEFAULT 0,
    total             NUMERIC(20, 2) NOT NULL DEFAULT 0,
    total_hpp         NUMERIC(20, 2),
    jenis_pembayaran  VARCHAR        NOT NULL DEFAULT 'TUNAI',
    -- Cache, bukan sumber kebenaran: selalu dihitung ulang dari alokasi
    -- pembayaran POSTED dan retur POSTED. Tidak boleh di-set manual lewat form.
    status_pembayaran VARCHAR        NOT NULL DEFAULT 'BELUM',
    status            VARCHAR        NOT NULL DEFAULT 'DRAFT',
    created_by        BIGINT         NOT NULL,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    posted_at         TIMESTAMPTZ,
    dibatalkan_oleh   BIGINT,
    alasan_batal      TEXT,

    CONSTRAINT penjualan_nomor_key UNIQUE (nomor)
);

CREATE INDEX penjualan_tanggal_idx           ON penjualan (tanggal);
CREATE INDEX penjualan_ruang_tanggal_idx     ON penjualan (id_ruang, tanggal);
CREATE INDEX penjualan_pelanggan_idx         ON penjualan (id_pelanggan);
CREATE INDEX penjualan_status_idx            ON penjualan (status);
CREATE INDEX penjualan_status_pembayaran_idx ON penjualan (status_pembayaran);

CREATE TABLE penjualan_detail (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_penjualan       BIGINT         NOT NULL,
    id_product         BIGINT         NOT NULL,
    qty_input          NUMERIC(18, 4) NOT NULL,
    id_satuan_input    BIGINT         NOT NULL,
    faktor_konversi    BIGINT         NOT NULL,
    qty_dasar          BIGINT         NOT NULL,
    id_harga_jual      BIGINT,
    harga_satuan_input NUMERIC(20, 2) NOT NULL,
    diskon_baris       NUMERIC(20, 2) NOT NULL DEFAULT 0,
    subtotal           NUMERIC(20, 2) NOT NULL,
    hpp_satuan_dasar   NUMERIC(20, 4),
    hpp_total          NUMERIC(20, 2),

    CONSTRAINT penjualan_detail_qty_dasar_check       CHECK (qty_dasar > 0),
    CONSTRAINT penjualan_detail_faktor_konversi_check CHECK (faktor_konversi > 0)
);

CREATE INDEX penjualan_detail_penjualan_idx ON penjualan_detail (id_penjualan);
CREATE INDEX penjualan_detail_product_idx   ON penjualan_detail (id_product);

-- Retur penjualan ikut mengurangi piutang. Bila tidak dihitung, invoice yang
-- barangnya sebagian dikembalikan akan selamanya terlihat kurang bayar.
CREATE TABLE retur_penjualan (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor        VARCHAR        NOT NULL,
    tanggal      TIMESTAMPTZ    NOT NULL,
    id_penjualan BIGINT         NOT NULL,
    id_pelanggan BIGINT,
    id_ruang     BIGINT         NOT NULL,
    alasan       TEXT,
    total        NUMERIC(20, 2) NOT NULL DEFAULT 0,
    total_hpp    NUMERIC(20, 2),
    status       VARCHAR        NOT NULL DEFAULT 'DRAFT',
    created_by   BIGINT         NOT NULL,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    posted_at    TIMESTAMPTZ,

    CONSTRAINT retur_penjualan_nomor_key UNIQUE (nomor)
);

CREATE INDEX retur_penjualan_tanggal_idx   ON retur_penjualan (tanggal);
CREATE INDEX retur_penjualan_penjualan_idx ON retur_penjualan (id_penjualan);

CREATE TABLE retur_penjualan_detail (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_retur_penjualan  BIGINT         NOT NULL,
    id_penjualan_detail BIGINT         NOT NULL,
    qty_input           NUMERIC(18, 4) NOT NULL,
    id_satuan_input     BIGINT         NOT NULL,
    faktor_konversi     BIGINT         NOT NULL,
    qty_dasar           BIGINT         NOT NULL,
    harga_satuan_input  NUMERIC(20, 2) NOT NULL,
    hpp_satuan_dasar    NUMERIC(20, 4) NOT NULL,
    nilai               NUMERIC(20, 2) NOT NULL,

    CONSTRAINT retur_penjualan_detail_qty_dasar_check       CHECK (qty_dasar > 0),
    CONSTRAINT retur_penjualan_detail_faktor_konversi_check CHECK (faktor_konversi > 0)
);

CREATE INDEX retur_penjualan_detail_retur_idx            ON retur_penjualan_detail (id_retur_penjualan);
CREATE INDEX retur_penjualan_detail_penjualan_detail_idx ON retur_penjualan_detail (id_penjualan_detail);

-- Giro belum cair bukan lunas: piutang baru berkurang saat status_giro = CAIR.
-- jumlah_dialokasikan boleh lebih kecil dari jumlah; sisanya menggantung
-- sebagai titipan untuk invoice berikutnya.
CREATE TABLE penerimaan_pembayaran (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor                    VARCHAR        NOT NULL,
    tanggal                  TIMESTAMPTZ    NOT NULL,
    id_pelanggan             BIGINT         NOT NULL,
    metode                   VARCHAR        NOT NULL,
    no_referensi             VARCHAR,
    nama_bank                VARCHAR,
    tanggal_jatuh_tempo_giro DATE,
    tanggal_cair             DATE,
    status_giro              VARCHAR,
    jumlah                   NUMERIC(20, 2) NOT NULL,
    jumlah_dialokasikan      NUMERIC(20, 2) NOT NULL DEFAULT 0,
    status                   VARCHAR        NOT NULL DEFAULT 'DRAFT',
    keterangan               TEXT,
    created_by               BIGINT         NOT NULL,
    created_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),
    posted_at                TIMESTAMPTZ,
    dibatalkan_oleh          BIGINT,
    alasan_batal             TEXT,

    CONSTRAINT penerimaan_pembayaran_nomor_key      UNIQUE (nomor),
    CONSTRAINT penerimaan_pembayaran_jumlah_check   CHECK (jumlah > 0),
    CONSTRAINT penerimaan_pembayaran_alokasi_check  CHECK (jumlah_dialokasikan >= 0 AND jumlah_dialokasikan <= jumlah)
);

CREATE INDEX penerimaan_pembayaran_tanggal_idx           ON penerimaan_pembayaran (tanggal);
CREATE INDEX penerimaan_pembayaran_pelanggan_tanggal_idx ON penerimaan_pembayaran (id_pelanggan, tanggal);
CREATE INDEX penerimaan_pembayaran_status_idx            ON penerimaan_pembayaran (status);

-- Pembayaran dan invoice adalah relasi banyak-ke-banyak: satu transfer menutup
-- belasan invoice, satu invoice bisa ditutup beberapa pembayaran. Itu sebabnya
-- alokasi jadi tabel tersendiri, bukan kolom di penjualan.
CREATE TABLE pembayaran_alokasi (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_penerimaan_pembayaran BIGINT         NOT NULL,
    id_penjualan             BIGINT         NOT NULL,
    jumlah                   NUMERIC(20, 2) NOT NULL,
    created_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT pembayaran_alokasi_jumlah_check CHECK (jumlah > 0)
);

CREATE INDEX pembayaran_alokasi_penerimaan_idx ON pembayaran_alokasi (id_penerimaan_pembayaran);
CREATE INDEX pembayaran_alokasi_penjualan_idx  ON pembayaran_alokasi (id_penjualan);

ALTER TABLE penjualan
    ADD CONSTRAINT penjualan_id_ruang_fkey        FOREIGN KEY (id_ruang) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penjualan_id_pelanggan_fkey    FOREIGN KEY (id_pelanggan) REFERENCES pelanggan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penjualan_created_by_fkey      FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penjualan_dibatalkan_oleh_fkey FOREIGN KEY (dibatalkan_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE penjualan_detail
    ADD CONSTRAINT penjualan_detail_id_penjualan_fkey    FOREIGN KEY (id_penjualan) REFERENCES penjualan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penjualan_detail_id_product_fkey      FOREIGN KEY (id_product) REFERENCES product (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penjualan_detail_id_satuan_input_fkey FOREIGN KEY (id_satuan_input) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penjualan_detail_id_harga_jual_fkey   FOREIGN KEY (id_harga_jual) REFERENCES product_harga_jual (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE retur_penjualan
    ADD CONSTRAINT retur_penjualan_id_penjualan_fkey FOREIGN KEY (id_penjualan) REFERENCES penjualan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT retur_penjualan_id_pelanggan_fkey FOREIGN KEY (id_pelanggan) REFERENCES pelanggan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT retur_penjualan_id_ruang_fkey     FOREIGN KEY (id_ruang) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT retur_penjualan_created_by_fkey   FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE retur_penjualan_detail
    ADD CONSTRAINT retur_penjualan_detail_id_retur_fkey        FOREIGN KEY (id_retur_penjualan) REFERENCES retur_penjualan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT retur_penjualan_detail_id_penj_detail_fkey  FOREIGN KEY (id_penjualan_detail) REFERENCES penjualan_detail (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT retur_penjualan_detail_id_satuan_input_fkey FOREIGN KEY (id_satuan_input) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE penerimaan_pembayaran
    ADD CONSTRAINT penerimaan_pembayaran_id_pelanggan_fkey    FOREIGN KEY (id_pelanggan) REFERENCES pelanggan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penerimaan_pembayaran_created_by_fkey      FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penerimaan_pembayaran_dibatalkan_oleh_fkey FOREIGN KEY (dibatalkan_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pembayaran_alokasi
    ADD CONSTRAINT pembayaran_alokasi_id_penerimaan_fkey FOREIGN KEY (id_penerimaan_pembayaran) REFERENCES penerimaan_pembayaran (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pembayaran_alokasi_id_penjualan_fkey  FOREIGN KEY (id_penjualan) REFERENCES penjualan (id) DEFERRABLE INITIALLY IMMEDIATE;
