-- Master data: identitas, tabel referensi, dan harga jual berversi.
-- btree_gist dibutuhkan exclusion constraint pada product_harga_jual di bawah.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TYPE jenis_transaksi AS ENUM (
    'PEMBELIAN',
    'RETUR_PEMBELIAN',
    'PENJUALAN',
    'RETUR_PENJUALAN',
    'PEMAKAIAN',
    'PEMBATALAN_PEMAKAIAN',
    'PEMBATALAN_TRANSAKSI',
    'MUTASI_KELUAR',
    'MUTASI_MASUK',
    'SO_SURPLUS',
    'SO_DEFISIT'
);

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR     NOT NULL,
    email        VARCHAR,
    password     VARCHAR     NOT NULL,
    nama_lengkap VARCHAR,
    role_active  BIGINT,
    is_aktif     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT users_username_key    UNIQUE (username),
    CONSTRAINT users_email_key       UNIQUE (email),
    CONSTRAINT users_role_active_key UNIQUE (role_active)
);

CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TABLE role (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR NOT NULL,
    CONSTRAINT role_nama_key UNIQUE (nama)
);

CREATE TABLE user_role (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
);

CREATE UNIQUE INDEX user_role_user_role_uidx ON user_role (user_id, role_id);

CREATE TABLE satuan (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR NOT NULL,
    CONSTRAINT satuan_nama_key UNIQUE (nama)
);

CREATE TABLE ruang (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode       VARCHAR,
    nama_ruang VARCHAR NOT NULL,
    is_aktif   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ruang_kode_key UNIQUE (kode)
);

CREATE TABLE product (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_barang     VARCHAR     NOT NULL,
    nama            VARCHAR     NOT NULL,
    id_satuan_dasar BIGINT      NOT NULL,
    stok_minimum    BIGINT      NOT NULL DEFAULT 0,
    is_aktif        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      BIGINT      NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    CONSTRAINT product_kode_barang_key    UNIQUE (kode_barang),
    CONSTRAINT product_stok_minimum_check CHECK (stok_minimum >= 0)
);

CREATE INDEX product_nama_idx ON product (nama);

CREATE TRIGGER product_set_updated_at
    BEFORE UPDATE ON product
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TABLE product_satuan (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_product       BIGINT  NOT NULL,
    id_satuan        BIGINT  NOT NULL,
    faktor           BIGINT  NOT NULL,
    is_default_input BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT product_satuan_faktor_check CHECK (faktor > 0)
);

CREATE UNIQUE INDEX product_satuan_product_satuan_uidx ON product_satuan (id_product, id_satuan);

CREATE TABLE product_harga_jual (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_product     BIGINT        NOT NULL,
    id_satuan      BIGINT        NOT NULL,
    harga          NUMERIC(20, 2) NOT NULL,
    berlaku_dari   DATE          NOT NULL,
    berlaku_sampai DATE,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by     BIGINT        NOT NULL,
    CONSTRAINT product_harga_jual_harga_check    CHECK (harga >= 0),
    CONSTRAINT product_harga_jual_periode_check  CHECK (berlaku_sampai IS NULL OR berlaku_sampai > berlaku_dari)
);

CREATE INDEX product_harga_jual_lookup_idx
    ON product_harga_jual (id_product, id_satuan, berlaku_dari);

-- Dua versi harga tidak boleh berlaku bersamaan untuk product+satuan yang sama.
-- Tanpa ini, penentuan "harga yang berlaku hari ini" jadi ambigu.
ALTER TABLE product_harga_jual
    ADD CONSTRAINT product_harga_jual_no_overlap EXCLUDE USING gist (
        id_product WITH =,
        id_satuan WITH =,
        daterange(berlaku_dari, berlaku_sampai, '[)') WITH &&
    );

CREATE TABLE supplier (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode       VARCHAR,
    nama       VARCHAR     NOT NULL,
    telepon    VARCHAR,
    alamat     TEXT,
    npwp       VARCHAR,
    is_aktif   BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    CONSTRAINT supplier_kode_key UNIQUE (kode)
);

CREATE TABLE pelanggan (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode          VARCHAR,
    nama          VARCHAR     NOT NULL,
    telepon       VARCHAR,
    alamat        TEXT,
    npwp          VARCHAR,
    plafon_kredit NUMERIC(20, 2),
    is_aktif      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by    BIGINT,
    CONSTRAINT pelanggan_kode_key           UNIQUE (kode),
    CONSTRAINT pelanggan_plafon_check       CHECK (plafon_kredit IS NULL OR plafon_kredit >= 0)
);

CREATE TABLE ekspedisi (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama     VARCHAR NOT NULL,
    telepon  VARCHAR,
    is_aktif BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE periode (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tahun        INT     NOT NULL,
    bulan        INT     NOT NULL,
    status       VARCHAR NOT NULL DEFAULT 'BUKA',
    ditutup_oleh BIGINT,
    ts_tutup     TIMESTAMPTZ,
    CONSTRAINT periode_bulan_check  CHECK (bulan BETWEEN 1 AND 12),
    CONSTRAINT periode_status_check CHECK (status IN ('BUKA', 'TUTUP'))
);

CREATE UNIQUE INDEX periode_tahun_bulan_uidx ON periode (tahun, bulan);

-- Foreign keys. users <-> user_role saling menunjuk, jadi keduanya dipasang
-- setelah kedua tabel ada.
ALTER TABLE users
    ADD CONSTRAINT users_role_active_fkey FOREIGN KEY (role_active) REFERENCES user_role (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE user_role
    ADD CONSTRAINT user_role_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT user_role_role_id_fkey FOREIGN KEY (role_id) REFERENCES role (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE product
    ADD CONSTRAINT product_id_satuan_dasar_fkey FOREIGN KEY (id_satuan_dasar) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT product_created_by_fkey      FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT product_updated_by_fkey      FOREIGN KEY (updated_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE product_satuan
    ADD CONSTRAINT product_satuan_id_product_fkey FOREIGN KEY (id_product) REFERENCES product (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT product_satuan_id_satuan_fkey  FOREIGN KEY (id_satuan) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE product_harga_jual
    ADD CONSTRAINT product_harga_jual_id_product_fkey FOREIGN KEY (id_product) REFERENCES product (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT product_harga_jual_id_satuan_fkey  FOREIGN KEY (id_satuan) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT product_harga_jual_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE supplier
    ADD CONSTRAINT supplier_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pelanggan
    ADD CONSTRAINT pelanggan_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE periode
    ADD CONSTRAINT periode_ditutup_oleh_fkey FOREIGN KEY (ditutup_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;
