-- Siklus pembelian dan returnya.
--
-- CATATAN: alokasi biaya angkut diubah di migrasi 000008 menjadi berbasis koli
-- (kolom pembelian_detail.jumlah_koli), dan default metode_alokasi_angkut
-- berubah dari 'QTY' menjadi 'KOLI'. Kolom jenis_pembayaran/status_pembayaran
-- juga ditambahkan di sana. Baca 000008 bersama file ini.
--
-- total_koli dan tarif_per_koli adalah catatan nota ekspedisi untuk
-- rekonsiliasi tagihan; biaya_angkut = total_koli * tarif_per_koli.
CREATE TABLE pembelian (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor                 VARCHAR        NOT NULL,
    tanggal               TIMESTAMPTZ    NOT NULL,
    id_supplier           BIGINT         NOT NULL,
    id_ruang              BIGINT         NOT NULL,
    no_faktur_supplier    VARCHAR,
    tanggal_faktur        DATE,
    subtotal              NUMERIC(20, 2) NOT NULL DEFAULT 0,
    diskon_nota           NUMERIC(20, 2) NOT NULL DEFAULT 0,
    ppn                   NUMERIC(20, 2) NOT NULL DEFAULT 0,
    -- true: PPN jadi pajak masukan, tidak masuk harga pokok.
    -- false: PPN ikut menjadi bagian harga pokok.
    ppn_dikreditkan       BOOLEAN        NOT NULL DEFAULT FALSE,
    pembulatan            NUMERIC(20, 2) NOT NULL DEFAULT 0,
    total                 NUMERIC(20, 2) NOT NULL DEFAULT 0,
    id_ekspedisi          BIGINT,
    no_resi               VARCHAR,
    total_koli            NUMERIC(10, 2),
    tarif_per_koli        NUMERIC(20, 2),
    biaya_angkut          NUMERIC(20, 2) NOT NULL DEFAULT 0,
    -- true: ongkir sudah termasuk nota supplier, tidak boleh dialokasikan lagi.
    ditanggung_supplier   BOOLEAN        NOT NULL DEFAULT FALSE,
    metode_alokasi_angkut VARCHAR        NOT NULL DEFAULT 'QTY',
    status                VARCHAR        NOT NULL DEFAULT 'DRAFT',
    created_by            BIGINT         NOT NULL,
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT now(),
    posted_at             TIMESTAMPTZ,
    dibatalkan_oleh       BIGINT,
    alasan_batal          TEXT,

    CONSTRAINT pembelian_nomor_key         UNIQUE (nomor),
    CONSTRAINT pembelian_biaya_angkut_check CHECK (biaya_angkut >= 0)
);

CREATE INDEX pembelian_tanggal_idx          ON pembelian (tanggal);
CREATE INDEX pembelian_supplier_tanggal_idx ON pembelian (id_supplier, tanggal);
CREATE INDEX pembelian_ruang_tanggal_idx    ON pembelian (id_ruang, tanggal);
CREATE INDEX pembelian_status_idx           ON pembelian (status);

-- harga_pokok_satuan_dasar = (subtotal + alokasi_biaya) / qty_dasar.
-- Angka inilah yang dikirim ke kartu stok, bukan harga_satuan_input dibagi
-- faktor_konversi. faktor_konversi disimpan sebagai snapshot supaya perubahan
-- master product_satuan tidak menulis ulang sejarah.
CREATE TABLE pembelian_detail (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pembelian             BIGINT         NOT NULL,
    id_product               BIGINT         NOT NULL,
    qty_input                NUMERIC(18, 4) NOT NULL,
    id_satuan_input          BIGINT         NOT NULL,
    faktor_konversi          BIGINT         NOT NULL,
    qty_dasar                BIGINT         NOT NULL,
    harga_satuan_input       NUMERIC(20, 2) NOT NULL,
    diskon_baris             NUMERIC(20, 2) NOT NULL DEFAULT 0,
    subtotal                 NUMERIC(20, 2) NOT NULL,
    alokasi_biaya            NUMERIC(20, 2) NOT NULL DEFAULT 0,
    harga_pokok_satuan_dasar NUMERIC(20, 4),

    CONSTRAINT pembelian_detail_qty_dasar_check       CHECK (qty_dasar > 0),
    CONSTRAINT pembelian_detail_faktor_konversi_check CHECK (faktor_konversi > 0)
);

CREATE INDEX pembelian_detail_pembelian_idx ON pembelian_detail (id_pembelian);
CREATE INDEX pembelian_detail_product_idx   ON pembelian_detail (id_product);

-- Retur wajib menunjuk baris detail dokumen asalnya; harga pokok disalin dari
-- sana, bukan dari rata-rata terkini. Tanpa itu, pembelian dan returnya tidak
-- saling menghapus dengan tepat.
CREATE TABLE retur_pembelian (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor        VARCHAR        NOT NULL,
    tanggal      TIMESTAMPTZ    NOT NULL,
    id_pembelian BIGINT         NOT NULL,
    id_supplier  BIGINT         NOT NULL,
    id_ruang     BIGINT         NOT NULL,
    alasan       TEXT,
    total        NUMERIC(20, 2) NOT NULL DEFAULT 0,
    status       VARCHAR        NOT NULL DEFAULT 'DRAFT',
    created_by   BIGINT         NOT NULL,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    posted_at    TIMESTAMPTZ,

    CONSTRAINT retur_pembelian_nomor_key UNIQUE (nomor)
);

CREATE INDEX retur_pembelian_tanggal_idx   ON retur_pembelian (tanggal);
CREATE INDEX retur_pembelian_pembelian_idx ON retur_pembelian (id_pembelian);

CREATE TABLE retur_pembelian_detail (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_retur_pembelian       BIGINT         NOT NULL,
    id_pembelian_detail      BIGINT         NOT NULL,
    qty_input                NUMERIC(18, 4) NOT NULL,
    id_satuan_input          BIGINT         NOT NULL,
    faktor_konversi          BIGINT         NOT NULL,
    qty_dasar                BIGINT         NOT NULL,
    harga_pokok_satuan_dasar NUMERIC(20, 4) NOT NULL,
    nilai                    NUMERIC(20, 2) NOT NULL,

    CONSTRAINT retur_pembelian_detail_qty_dasar_check       CHECK (qty_dasar > 0),
    CONSTRAINT retur_pembelian_detail_faktor_konversi_check CHECK (faktor_konversi > 0)
);

CREATE INDEX retur_pembelian_detail_retur_idx           ON retur_pembelian_detail (id_retur_pembelian);
CREATE INDEX retur_pembelian_detail_pembelian_detail_idx ON retur_pembelian_detail (id_pembelian_detail);

ALTER TABLE pembelian
    ADD CONSTRAINT pembelian_id_supplier_fkey     FOREIGN KEY (id_supplier) REFERENCES supplier (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pembelian_id_ruang_fkey        FOREIGN KEY (id_ruang) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pembelian_id_ekspedisi_fkey    FOREIGN KEY (id_ekspedisi) REFERENCES ekspedisi (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pembelian_created_by_fkey      FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pembelian_dibatalkan_oleh_fkey FOREIGN KEY (dibatalkan_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pembelian_detail
    ADD CONSTRAINT pembelian_detail_id_pembelian_fkey    FOREIGN KEY (id_pembelian) REFERENCES pembelian (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pembelian_detail_id_product_fkey      FOREIGN KEY (id_product) REFERENCES product (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pembelian_detail_id_satuan_input_fkey FOREIGN KEY (id_satuan_input) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE retur_pembelian
    ADD CONSTRAINT retur_pembelian_id_pembelian_fkey FOREIGN KEY (id_pembelian) REFERENCES pembelian (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT retur_pembelian_id_supplier_fkey  FOREIGN KEY (id_supplier) REFERENCES supplier (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT retur_pembelian_id_ruang_fkey     FOREIGN KEY (id_ruang) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT retur_pembelian_created_by_fkey   FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE retur_pembelian_detail
    ADD CONSTRAINT retur_pembelian_detail_id_retur_fkey        FOREIGN KEY (id_retur_pembelian) REFERENCES retur_pembelian (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT retur_pembelian_detail_id_pemb_detail_fkey  FOREIGN KEY (id_pembelian_detail) REFERENCES pembelian_detail (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT retur_pembelian_detail_id_satuan_input_fkey FOREIGN KEY (id_satuan_input) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE;
