-- Pemakaian internal, mutasi antar ruang, dan stok opname.

-- Alur status:
--   DRAFT -> DIAJUKAN -> DISETUJUI -> DIPOSTING
--                    \-> DITOLAK        \-> DIBATALKAN
-- DITOLAK tidak pernah menghasilkan baris kartu stok, jadi tidak butuh pembalik.
CREATE TABLE pemakaian (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor               VARCHAR        NOT NULL,
    tanggal             TIMESTAMPTZ    NOT NULL,
    id_ruang            BIGINT         NOT NULL,
    id_pemohon          BIGINT         NOT NULL,
    keperluan           TEXT           NOT NULL,
    status              VARCHAR        NOT NULL DEFAULT 'DRAFT',
    disetujui_oleh      BIGINT,
    ts_disetujui        TIMESTAMPTZ,
    catatan_persetujuan TEXT,
    total_hpp           NUMERIC(20, 2),
    created_by          BIGINT         NOT NULL,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    posted_at           TIMESTAMPTZ,
    dibatalkan_oleh     BIGINT,
    alasan_batal        TEXT,

    CONSTRAINT pemakaian_nomor_key UNIQUE (nomor),
    CONSTRAINT pemakaian_status_check CHECK (
        status IN ('DRAFT', 'DIAJUKAN', 'DISETUJUI', 'DITOLAK', 'DIPOSTING', 'DIBATALKAN')
    ),
    -- Pemohon tidak boleh menyetujui permintaannya sendiri.
    CONSTRAINT pemakaian_penyetuju_check CHECK (disetujui_oleh IS NULL OR disetujui_oleh <> id_pemohon)
);

CREATE INDEX pemakaian_tanggal_idx       ON pemakaian (tanggal);
CREATE INDEX pemakaian_ruang_tanggal_idx ON pemakaian (id_ruang, tanggal);
CREATE INDEX pemakaian_status_idx        ON pemakaian (status);
CREATE INDEX pemakaian_pemohon_idx       ON pemakaian (id_pemohon);

-- Yang masuk kartu stok adalah qty_disetujui_dasar, bukan qty_dasar. Nilai 0
-- berarti item ditolak meski notanya disetujui. Selisih diminta vs disetujui
-- tetap tersimpan sebagai data perencanaan.
CREATE TABLE pemakaian_detail (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pemakaian        BIGINT         NOT NULL,
    id_product          BIGINT         NOT NULL,
    qty_input           NUMERIC(18, 4) NOT NULL,
    id_satuan_input     BIGINT         NOT NULL,
    faktor_konversi     BIGINT         NOT NULL,
    qty_dasar           BIGINT         NOT NULL,
    qty_disetujui_dasar BIGINT,
    hpp_satuan_dasar    NUMERIC(20, 4),
    hpp_total           NUMERIC(20, 2),
    keterangan          TEXT,

    CONSTRAINT pemakaian_detail_qty_dasar_check       CHECK (qty_dasar > 0),
    CONSTRAINT pemakaian_detail_faktor_konversi_check CHECK (faktor_konversi > 0),
    CONSTRAINT pemakaian_detail_qty_disetujui_check   CHECK (
        qty_disetujui_dasar IS NULL OR (qty_disetujui_dasar >= 0 AND qty_disetujui_dasar <= qty_dasar)
    )
);

CREATE INDEX pemakaian_detail_pemakaian_idx ON pemakaian_detail (id_pemakaian);
CREATE INDEX pemakaian_detail_product_idx   ON pemakaian_detail (id_product);

-- Satu baris detail menghasilkan dua baris kartu stok: MUTASI_KELUAR di ruang
-- asal dan MUTASI_MASUK di ruang tujuan. Harga pokok wajib mengikuti ruang
-- asal, kalau tidak memindahkan barang bisa mengubah total nilai persediaan.
CREATE TABLE mutasi (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor           VARCHAR     NOT NULL,
    tanggal         TIMESTAMPTZ NOT NULL,
    id_ruang_asal   BIGINT      NOT NULL,
    id_ruang_tujuan BIGINT      NOT NULL,
    keterangan      TEXT,
    status          VARCHAR     NOT NULL DEFAULT 'DRAFT',
    created_by      BIGINT      NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    posted_at       TIMESTAMPTZ,

    CONSTRAINT mutasi_nomor_key  UNIQUE (nomor),
    CONSTRAINT mutasi_ruang_check CHECK (id_ruang_asal <> id_ruang_tujuan)
);

CREATE INDEX mutasi_tanggal_idx             ON mutasi (tanggal);
CREATE INDEX mutasi_ruang_asal_tanggal_idx  ON mutasi (id_ruang_asal, tanggal);
CREATE INDEX mutasi_ruang_tujuan_tanggal_idx ON mutasi (id_ruang_tujuan, tanggal);

CREATE TABLE mutasi_detail (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mutasi                BIGINT         NOT NULL,
    id_product               BIGINT         NOT NULL,
    qty_input                NUMERIC(18, 4) NOT NULL,
    id_satuan_input          BIGINT         NOT NULL,
    faktor_konversi          BIGINT         NOT NULL,
    qty_dasar                BIGINT         NOT NULL,
    harga_pokok_satuan_dasar NUMERIC(20, 4),

    CONSTRAINT mutasi_detail_qty_dasar_check       CHECK (qty_dasar > 0),
    CONSTRAINT mutasi_detail_faktor_konversi_check CHECK (faktor_konversi > 0)
);

CREATE INDEX mutasi_detail_mutasi_idx  ON mutasi_detail (id_mutasi);
CREATE INDEX mutasi_detail_product_idx ON mutasi_detail (id_product);

-- ts_cutoff ada di header karena itu properti sesi opname, bukan per baris.
CREATE TABLE stok_opname (
    idstok_opname BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor         VARCHAR     NOT NULL,
    id_ruang      BIGINT      NOT NULL,
    tgl_buka      DATE        NOT NULL,
    tgl_tutup     DATE,
    ts_cutoff     TIMESTAMPTZ NOT NULL,
    uraian_so     TEXT,
    status        VARCHAR     NOT NULL DEFAULT 'DRAFT',
    created_by    BIGINT      NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    verified_by   BIGINT,
    ts_verified   TIMESTAMPTZ,
    posted_at     TIMESTAMPTZ,

    CONSTRAINT stok_opname_nomor_key   UNIQUE (nomor),
    CONSTRAINT stok_opname_tanggal_check CHECK (tgl_tutup IS NULL OR tgl_tutup >= tgl_buka)
);

CREATE INDEX stok_opname_ruang_buka_idx ON stok_opname (id_ruang, tgl_buka);
CREATE INDEX stok_opname_status_idx     ON stok_opname (status);

-- id_kartu_stok_cutoff menunjuk baris acuan saldo sistem.
-- id_kartu_stok_penyesuaian menunjuk baris SO_SURPLUS/SO_DEFISIT yang
-- dihasilkan, dan null sampai diposting.
CREATE TABLE stok_opname_detail (
    idstok_opname_detail      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_stok_opname            BIGINT      NOT NULL,
    id_barang                 BIGINT      NOT NULL,
    id_ruang                  BIGINT      NOT NULL,
    stok_awal                 BIGINT      NOT NULL DEFAULT 0,
    stok_so                   BIGINT,
    stok_selisih_lebih        BIGINT      NOT NULL DEFAULT 0,
    stok_selisih_kurang       BIGINT      NOT NULL DEFAULT 0,
    keterangan                TEXT,
    id_kartu_stok_cutoff      BIGINT      NOT NULL,
    id_kartu_stok_penyesuaian BIGINT,
    updated_by                BIGINT,
    ts_update                 TIMESTAMPTZ,

    CONSTRAINT stok_opname_detail_stok_so_check  CHECK (stok_so IS NULL OR stok_so >= 0),
    CONSTRAINT stok_opname_detail_selisih_check  CHECK (
        stok_selisih_lebih >= 0
        AND stok_selisih_kurang >= 0
        AND NOT (stok_selisih_lebih > 0 AND stok_selisih_kurang > 0)
    )
);

CREATE UNIQUE INDEX stok_opname_detail_unik_uidx ON stok_opname_detail (id_stok_opname, id_barang, id_ruang);
CREATE INDEX stok_opname_detail_barang_idx       ON stok_opname_detail (id_barang);

ALTER TABLE pemakaian
    ADD CONSTRAINT pemakaian_id_ruang_fkey        FOREIGN KEY (id_ruang) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pemakaian_id_pemohon_fkey      FOREIGN KEY (id_pemohon) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pemakaian_disetujui_oleh_fkey  FOREIGN KEY (disetujui_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pemakaian_created_by_fkey      FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pemakaian_dibatalkan_oleh_fkey FOREIGN KEY (dibatalkan_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pemakaian_detail
    ADD CONSTRAINT pemakaian_detail_id_pemakaian_fkey    FOREIGN KEY (id_pemakaian) REFERENCES pemakaian (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pemakaian_detail_id_product_fkey      FOREIGN KEY (id_product) REFERENCES product (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pemakaian_detail_id_satuan_input_fkey FOREIGN KEY (id_satuan_input) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE mutasi
    ADD CONSTRAINT mutasi_id_ruang_asal_fkey   FOREIGN KEY (id_ruang_asal) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT mutasi_id_ruang_tujuan_fkey FOREIGN KEY (id_ruang_tujuan) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT mutasi_created_by_fkey      FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE mutasi_detail
    ADD CONSTRAINT mutasi_detail_id_mutasi_fkey       FOREIGN KEY (id_mutasi) REFERENCES mutasi (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT mutasi_detail_id_product_fkey      FOREIGN KEY (id_product) REFERENCES product (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT mutasi_detail_id_satuan_input_fkey FOREIGN KEY (id_satuan_input) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stok_opname
    ADD CONSTRAINT stok_opname_id_ruang_fkey    FOREIGN KEY (id_ruang) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT stok_opname_created_by_fkey  FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT stok_opname_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE stok_opname_detail
    ADD CONSTRAINT stok_opname_detail_id_stok_opname_fkey FOREIGN KEY (id_stok_opname) REFERENCES stok_opname (idstok_opname) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT stok_opname_detail_id_barang_fkey      FOREIGN KEY (id_barang) REFERENCES product (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT stok_opname_detail_id_ruang_fkey       FOREIGN KEY (id_ruang) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT stok_opname_detail_ks_cutoff_fkey      FOREIGN KEY (id_kartu_stok_cutoff) REFERENCES kartu_stok (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT stok_opname_detail_ks_penyesuaian_fkey FOREIGN KEY (id_kartu_stok_penyesuaian) REFERENCES kartu_stok (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT stok_opname_detail_updated_by_fkey     FOREIGN KEY (updated_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;
