-- Sisi utang supplier (cermin dari sisi piutang) dan alokasi biaya angkut
-- berbasis koli.
--
-- Perubahan arah desain: koli sebelumnya ditolak sebagai dasar alokasi karena
-- satu koli bisa berisi campuran barang. Sekarang dipakai, dengan jumlah_koli
-- desimal per baris supaya satu baris boleh menempati sebagian koli. Angka itu
-- diisi petugas gudang saat membongkar kiriman, jadi pengamannya ada di
-- aplikasi (lihat catatan di bawah), bukan di database.

ALTER TABLE pembelian
    ADD COLUMN jenis_pembayaran  VARCHAR NOT NULL DEFAULT 'TUNAI',
    -- Cache seperti penjualan.status_pembayaran: selalu dihitung ulang dari
    -- alokasi POSTED dan retur POSTED, tidak pernah di-set manual.
    ADD COLUMN status_pembayaran VARCHAR NOT NULL DEFAULT 'BELUM',
    -- biaya_angkut = total_koli * tarif_per_koli, dialokasikan proporsional
    -- terhadap jumlah_koli tiap baris.
    ALTER COLUMN metode_alokasi_angkut SET DEFAULT 'KOLI';

CREATE INDEX pembelian_status_pembayaran_idx ON pembelian (status_pembayaran);

ALTER TABLE pembelian_detail
    ADD COLUMN jumlah_koli NUMERIC(10, 2) NOT NULL DEFAULT 0,
    ADD CONSTRAINT pembelian_detail_jumlah_koli_check CHECK (jumlah_koli >= 0);

-- Cermin penerimaan_pembayaran, arah uang terbalik. Satu pembayaran menutup
-- beberapa faktur; satu faktur bisa dicicil beberapa pembayaran. Giro yang
-- belum cair belum mengurangi utang.
CREATE TABLE pembayaran_utang (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor                    VARCHAR        NOT NULL,
    tanggal                  TIMESTAMPTZ    NOT NULL,
    id_supplier              BIGINT         NOT NULL,
    metode                   VARCHAR        NOT NULL,
    no_referensi             VARCHAR,
    nama_bank                VARCHAR,
    tanggal_jatuh_tempo_giro DATE,
    tanggal_cair             DATE,
    status_giro              VARCHAR,
    jumlah                   NUMERIC(20, 2) NOT NULL,
    jumlah_dialokasikan      NUMERIC(20, 2) NOT NULL DEFAULT 0,
    status                   VARCHAR        NOT NULL DEFAULT 'DRAFT',
    keterangan               TEXT,
    created_by               BIGINT         NOT NULL,
    created_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),
    posted_at                TIMESTAMPTZ,
    dibatalkan_oleh          BIGINT,
    alasan_batal             TEXT,

    CONSTRAINT pembayaran_utang_nomor_key     UNIQUE (nomor),
    CONSTRAINT pembayaran_utang_jumlah_check  CHECK (jumlah > 0),
    CONSTRAINT pembayaran_utang_alokasi_check CHECK (jumlah_dialokasikan >= 0 AND jumlah_dialokasikan <= jumlah)
);

CREATE INDEX pembayaran_utang_tanggal_idx          ON pembayaran_utang (tanggal);
CREATE INDEX pembayaran_utang_supplier_tanggal_idx ON pembayaran_utang (id_supplier, tanggal);
CREATE INDEX pembayaran_utang_status_idx           ON pembayaran_utang (status);

CREATE TABLE pembayaran_utang_alokasi (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pembayaran_utang BIGINT         NOT NULL,
    id_pembelian        BIGINT         NOT NULL,
    jumlah              NUMERIC(20, 2) NOT NULL,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT pembayaran_utang_alokasi_jumlah_check CHECK (jumlah > 0)
);

CREATE INDEX pembayaran_utang_alokasi_pembayaran_idx ON pembayaran_utang_alokasi (id_pembayaran_utang);
CREATE INDEX pembayaran_utang_alokasi_pembelian_idx  ON pembayaran_utang_alokasi (id_pembelian);

ALTER TABLE pembayaran_utang
    ADD CONSTRAINT pembayaran_utang_id_supplier_fkey     FOREIGN KEY (id_supplier) REFERENCES supplier (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pembayaran_utang_created_by_fkey      FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pembayaran_utang_dibatalkan_oleh_fkey FOREIGN KEY (dibatalkan_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pembayaran_utang_alokasi
    ADD CONSTRAINT pembayaran_utang_alokasi_pembayaran_fkey FOREIGN KEY (id_pembayaran_utang) REFERENCES pembayaran_utang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT pembayaran_utang_alokasi_pembelian_fkey  FOREIGN KEY (id_pembelian) REFERENCES pembelian (id) DEFERRABLE INITIALLY IMMEDIATE;
