DROP TABLE IF EXISTS stok_opname_detail CASCADE;
DROP TABLE IF EXISTS stok_opname CASCADE;
DROP TABLE IF EXISTS mutasi_detail CASCADE;
DROP TABLE IF EXISTS mutasi CASCADE;
DROP TABLE IF EXISTS pemakaian_detail CASCADE;
DROP TABLE IF EXISTS pemakaian CASCADE;
