-- Penerimaan susulan: kiriman kedua untuk barang yang belum datang di kiriman
-- pertama (isu #4 fase 3).
--
-- Premisnya bukan penerimaan parsial yang umum di ERP. Di sini supplier kehabisan
-- stok lalu mengirim yang ada dulu, tidak direncanakan, dan **fakturnya tetap satu**
-- serta terbit penuh di kiriman pertama. Jadi:
--
--   utang     -> sudah dibukukan penuh di pembelian, dokumen ini tidak menambahnya
--   stok      -> naik saat dokumen ini diposting
--   yang dilacak -> cuma sisa per baris
--
-- Bentuknya cermin dari retur_pembelian: sama-sama menunjuk pembelian_detail,
-- arah barangnya saja yang berlawanan. Dokumen pembelian yang sudah POSTED tidak
-- boleh diubah dan kartu_stok bersifat append-only, jadi menaikkan qty_diterima
-- pada baris yang sudah diposting bukan pilihan -- itu akan melanggar imutabilitas
-- dokumen, membuat pembatalan mustahil diaudit (baris kartu_stok mana yang harus
-- dibalik?), dan menghapus jejak kapan susulan benar-benar datang.

-- Nilai enum baru supaya laporan mutasi stok bisa memisahkan barang yang datang di
-- kiriman pertama dari yang menyusul, tanpa join ke tabel dokumen. Angka itu justru
-- menarik: ia menunjukkan seberapa sering supplier mengirim tidak lengkap.
--
-- ALTER TYPE ... ADD VALUE aman di dalam transaksi sejak PostgreSQL 12 selama
-- nilainya tidak dipakai di transaksi yang sama. Migrasi ini hanya menambahkannya.
ALTER TYPE jenis_transaksi ADD VALUE IF NOT EXISTS 'PENERIMAAN_SUSULAN';

-- id_supplier dan id_ruang disalin dari pembelian, bukan dipilih pemanggil.
-- Susulan adalah sisa dari dokumen itu: suppliernya sudah tertentu, dan ruangnya
-- sudah ditetapkan dokumen asal. Kalau barangnya perlu pindah ruang setelah
-- diterima, itu pekerjaan mutasi, bukan penerimaan.
--
-- Tidak ada kolom ongkir. Nilai yang masuk kartu stok adalah porsi sisa dari nilai
-- faktur asli, jadi total nilai persediaan dari satu faktur tetap persis sebesar
-- faktur itu berapa pun kali barangnya datang.
CREATE TABLE penerimaan_susulan (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor           VARCHAR        NOT NULL,
    tanggal         TIMESTAMPTZ    NOT NULL,
    id_pembelian    BIGINT         NOT NULL,
    id_supplier     BIGINT         NOT NULL,
    id_ruang        BIGINT         NOT NULL,
    keterangan      TEXT,
    -- Nilai barang yang menyusul, bukan tagihan. Dihitung ulang dari barisnya,
    -- tidak pernah di-set dari form.
    total_nilai     NUMERIC(20, 2) NOT NULL DEFAULT 0,
    status          VARCHAR        NOT NULL DEFAULT 'DRAFT',
    created_by      BIGINT         NOT NULL,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    diajukan_oleh   BIGINT,
    diajukan_pada   TIMESTAMPTZ,
    disetujui_oleh  BIGINT,
    disetujui_pada  TIMESTAMPTZ,
    posted_at       TIMESTAMPTZ,
    -- Kolom pembatalan ada di sini, tidak seperti retur_pembelian yang tidak
    -- punya. Dokumen ini menulis kartu_stok, jadi ia harus bisa dibalik -- dan
    -- pembalikan tanpa catatan siapa dan kenapa tidak bisa dibedakan dari
    -- kekeliruan.
    dibatalkan_oleh BIGINT,
    alasan_batal    TEXT,
    alasan_tolak    TEXT,

    CONSTRAINT penerimaan_susulan_nomor_key   UNIQUE (nomor),
    CONSTRAINT penerimaan_susulan_status_check
        CHECK (status IN ('DRAFT', 'DIAJUKAN', 'POSTED', 'BATAL')),
    CONSTRAINT penerimaan_susulan_total_nilai_check CHECK (total_nilai >= 0)
);

CREATE INDEX penerimaan_susulan_tanggal_id_idx ON penerimaan_susulan (tanggal DESC, id DESC);
CREATE INDEX penerimaan_susulan_pembelian_idx  ON penerimaan_susulan (id_pembelian);
CREATE INDEX penerimaan_susulan_status_idx     ON penerimaan_susulan (status);

-- harga_pokok_satuan_dasar disalin dari pembelian_detail, bukan dihitung ulang dan
-- bukan dibaca dari rata-rata terkini. Faktur menetapkan berapa barang ini
-- berharga; kiriman keduanya tidak mengubahnya. Menyalinnya juga yang membuat
-- pembelian dan susulannya berjumlah persis nilai faktur.
--
-- Karena itu dokumen asalnya wajib sudah POSTED: sebelum itu
-- pembelian_detail.harga_pokok_satuan_dasar masih NULL.
CREATE TABLE penerimaan_susulan_detail (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_penerimaan_susulan    BIGINT         NOT NULL,
    id_pembelian_detail      BIGINT         NOT NULL,
    qty_input                NUMERIC(18, 4) NOT NULL,
    id_satuan_input          BIGINT         NOT NULL,
    faktor_konversi          BIGINT         NOT NULL,
    qty_dasar                BIGINT         NOT NULL,
    harga_pokok_satuan_dasar NUMERIC(20, 4) NOT NULL,
    nilai                    NUMERIC(20, 2) NOT NULL,

    CONSTRAINT penerimaan_susulan_detail_qty_dasar_check       CHECK (qty_dasar > 0),
    CONSTRAINT penerimaan_susulan_detail_faktor_konversi_check CHECK (faktor_konversi > 0),
    CONSTRAINT penerimaan_susulan_detail_nilai_check           CHECK (nilai >= 0)
);

CREATE INDEX penerimaan_susulan_detail_susulan_idx ON penerimaan_susulan_detail (id_penerimaan_susulan);

-- Sisa dijumlahkan per baris pembelian, jadi indeks ini yang membuat pembacaannya
-- tidak memindai seluruh tabel.
CREATE INDEX penerimaan_susulan_detail_pembelian_detail_idx
    ON penerimaan_susulan_detail (id_pembelian_detail);

-- Satu baris pembelian hanya boleh muncul sekali per dokumen susulan. Tanpa ini,
-- dua baris untuk sumber yang sama akan lolos pengecekan sisa sendiri-sendiri lalu
-- bersama-sama melebihinya.
CREATE UNIQUE INDEX penerimaan_susulan_detail_baris_uidx
    ON penerimaan_susulan_detail (id_penerimaan_susulan, id_pembelian_detail);

ALTER TABLE penerimaan_susulan
    ADD CONSTRAINT penerimaan_susulan_id_pembelian_fkey
        FOREIGN KEY (id_pembelian) REFERENCES pembelian (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penerimaan_susulan_id_supplier_fkey
        FOREIGN KEY (id_supplier) REFERENCES supplier (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penerimaan_susulan_id_ruang_fkey
        FOREIGN KEY (id_ruang) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penerimaan_susulan_created_by_fkey
        FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penerimaan_susulan_diajukan_oleh_fkey
        FOREIGN KEY (diajukan_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penerimaan_susulan_disetujui_oleh_fkey
        FOREIGN KEY (disetujui_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penerimaan_susulan_dibatalkan_oleh_fkey
        FOREIGN KEY (dibatalkan_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE penerimaan_susulan_detail
    ADD CONSTRAINT penerimaan_susulan_detail_id_susulan_fkey
        FOREIGN KEY (id_penerimaan_susulan) REFERENCES penerimaan_susulan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penerimaan_susulan_detail_id_pembelian_detail_fkey
        FOREIGN KEY (id_pembelian_detail) REFERENCES pembelian_detail (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT penerimaan_susulan_detail_id_satuan_input_fkey
        FOREIGN KEY (id_satuan_input) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE;
