-- Saldo awal: stok pembukaan untuk unit kerja yang baru migrasi (isu #43).
--
-- Unit yang baru bergabung sudah memegang barang di raknya sebelum baris pertama
-- masuk ke sistem ini, dan tidak ada dokumen asal untuk disalin: bukan
-- stok_opname (id_kartu_stok_cutoff NOT NULL, barang tanpa riwayat tidak punya apa
-- pun untuk ditunjuk), bukan pembelian (melahirkan utang dan meracuni riwayat_beli),
-- bukan mutasi (menuntut ruang sumber yang sudah memegang stoknya).
--
-- Ini satu-satunya dokumen di proyek ini yang harga pokoknya DIKETIK. Karena itu
-- yang menentukan bukan alur kerjanya, melainkan pagarnya: satu (barang, ruang)
-- seumur hidup, ditegakkan di Go (SaldoAwalUseCase.Posting, setelah kunci saldo
-- dipegang) karena tidak ada constraint yang bisa membandingkan sebuah baris dengan
-- isi tabel lain. Migrasi ini hanya menyediakan tempat dan kosakatanya.

-- Nilai enum baru. Menumpang 'SO_SURPLUS' menggoda tapi berbohong: laporan
-- pergerakan mengelompokkan per jenis_transaksi, dan migrasi akan terbaca sebagai
-- temuan hasil opname.
--
-- ALTER TYPE ... ADD VALUE aman di dalam transaksi sejak PostgreSQL 12 selama
-- nilainya tidak dipakai di transaksi yang sama. Migrasi ini hanya menambahkannya
-- dan tidak menyisipkan baris kartu_stok apa pun.
ALTER TYPE jenis_transaksi ADD VALUE IF NOT EXISTS 'SALDO_AWAL';

-- Tidak ada id_supplier, no_faktur, atau kolom uang terutang, dan tidak boleh
-- ditambahkan "untuk berjaga-jaga": begitu ada satu saja, modul ini menjadi
-- pembelian kedua dengan pagar yang lebih longgar. Satu-satunya angka uang adalah
-- nilai yang masuk ke persediaan.
--
-- tanggal adalah DATE: tanggal cutover migrasi. Baris kartu_stok yang dihasilkannya
-- bertanggal ini, bukan now() -- fakta tentang rak pada saat itu.
--
-- total_nilai nullable: tidak punya jawaban sebelum posting, diisi sekali setelah
-- loop posting (bentuk pemakaian.total_hpp).
--
-- alasan wajib: satu-satunya catatan mengapa nilai persediaan diciptakan tanpa
-- dokumen di belakangnya.
CREATE TABLE saldo_awal (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor           VARCHAR        NOT NULL,
    tanggal         DATE           NOT NULL,
    id_ruang        BIGINT         NOT NULL,
    alasan          TEXT           NOT NULL,
    status          VARCHAR        NOT NULL DEFAULT 'DRAFT',
    total_nilai     NUMERIC(20, 2),
    created_by      BIGINT         NOT NULL,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    diajukan_oleh   BIGINT,
    diajukan_pada   TIMESTAMPTZ,
    disetujui_oleh  BIGINT,
    disetujui_pada  TIMESTAMPTZ,
    posted_at       TIMESTAMPTZ,
    dibatalkan_oleh BIGINT,
    alasan_batal    TEXT,
    alasan_tolak    TEXT,

    CONSTRAINT saldo_awal_nomor_key UNIQUE (nomor),
    -- Kosakata status dijaga CHECK, bukan enum baru (sejak 000028).
    CONSTRAINT saldo_awal_status_check
        CHECK (status IN ('DRAFT', 'DIAJUKAN', 'POSTED', 'BATAL')),
    CONSTRAINT saldo_awal_alasan_check CHECK (btrim(alasan) <> ''),
    CONSTRAINT saldo_awal_total_nilai_check CHECK (total_nilai IS NULL OR total_nilai >= 0)
);

CREATE INDEX saldo_awal_tanggal_id_idx ON saldo_awal (tanggal DESC, id DESC);
CREATE INDEX saldo_awal_status_idx     ON saldo_awal (status);
CREATE INDEX saldo_awal_ruang_idx      ON saldo_awal (id_ruang);

-- nilai_masuk = qty_input x harga_satuan_input, dihitung dari angka yang diketik dan
-- dibulatkan sekali, bukan dari hasil bagi. harga_pokok_satuan_dasar = harga /
-- faktor_konversi hanya diturunkan untuk dibaca; nilai totalnya tidak lewat
-- pembagian itu, jadi tidak ada sen yang hilang.
--
-- id_kartu_stok nullable: diisi saat posting dari RETURNING. Ia MENUNJUK kartu_stok,
-- kebalikan dari hampir semua tabel dokumen -- sehingga truncateMaster harus
-- menghapus saldo_awal* sebelum kartu_stok, bersama stok_opname*.
CREATE TABLE saldo_awal_detail (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_saldo_awal            BIGINT         NOT NULL,
    id_product               BIGINT         NOT NULL,
    qty_input                NUMERIC(18, 4) NOT NULL,
    id_satuan_input          BIGINT         NOT NULL,
    faktor_konversi          BIGINT         NOT NULL,
    qty_dasar                BIGINT         NOT NULL,
    harga_satuan_input       NUMERIC(20, 2) NOT NULL,
    harga_pokok_satuan_dasar NUMERIC(20, 4) NOT NULL,
    nilai_masuk              NUMERIC(20, 2) NOT NULL,
    id_kartu_stok            BIGINT,

    CONSTRAINT saldo_awal_detail_qty_input_check       CHECK (qty_input > 0),
    CONSTRAINT saldo_awal_detail_qty_dasar_check       CHECK (qty_dasar > 0),
    CONSTRAINT saldo_awal_detail_faktor_konversi_check CHECK (faktor_konversi > 0),
    -- Harga nol ditolak dengan sengaja. Barang yang benar-benar gratis akan menyeret
    -- rata-rata bergerak ruang itu ke bawah secara permanen, dan kasus itu tidak
    -- cukup sering untuk membuka lubang di satu-satunya dokumen yang nilainya
    -- diketik. Bila memang perlu, itu pembelian dengan diskon penuh, bukan ini.
    CONSTRAINT saldo_awal_detail_harga_check           CHECK (harga_satuan_input > 0),
    CONSTRAINT saldo_awal_detail_nilai_masuk_check     CHECK (nilai_masuk > 0)
);

CREATE INDEX saldo_awal_detail_saldo_awal_idx ON saldo_awal_detail (id_saldo_awal);

-- Wajib, dan berbeda dari mutasi/pemakaian yang sengaja tidak punya. Di sana
-- kuotanya adalah saldo ruang, jadi dua baris produk sama dijumlahkan dulu lalu
-- dicek. Di sini kuotanya "tepat satu, selamanya": dua baris untuk produk yang
-- sama akan sama-sama lolos pemeriksaan (keduanya membaca "belum ada riwayat")
-- lalu sama-sama menulis. Argumen yang sama persis dengan
-- penerimaan_susulan_detail_baris_uidx.
CREATE UNIQUE INDEX saldo_awal_detail_baris_uidx
    ON saldo_awal_detail (id_saldo_awal, id_product);

ALTER TABLE saldo_awal
    ADD CONSTRAINT saldo_awal_id_ruang_fkey
        FOREIGN KEY (id_ruang) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT saldo_awal_created_by_fkey
        FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT saldo_awal_diajukan_oleh_fkey
        FOREIGN KEY (diajukan_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT saldo_awal_disetujui_oleh_fkey
        FOREIGN KEY (disetujui_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT saldo_awal_dibatalkan_oleh_fkey
        FOREIGN KEY (dibatalkan_oleh) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE saldo_awal_detail
    ADD CONSTRAINT saldo_awal_detail_id_saldo_awal_fkey
        FOREIGN KEY (id_saldo_awal) REFERENCES saldo_awal (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT saldo_awal_detail_id_product_fkey
        FOREIGN KEY (id_product) REFERENCES product (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT saldo_awal_detail_id_satuan_input_fkey
        FOREIGN KEY (id_satuan_input) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT saldo_awal_detail_id_kartu_stok_fkey
        FOREIGN KEY (id_kartu_stok) REFERENCES kartu_stok (id) DEFERRABLE INITIALLY IMMEDIATE;
