-- Isu #40: presensi karyawan. Satu tombol masuk, satu tombol pulang, dua shift
-- per hari.
--
-- Modul pertama di proyek ini yang tidak menyentuh kartu_stok maupun uang: tidak
-- ada periode, tidak ada pembekuan ruang, tidak ada document_counter, tidak ada
-- nilai NUMERIC sama sekali. Yang tersisa dari kebiasaan proyek ini hanya yang
-- memang relevan: kosakata status dijaga CHECK (bukan enum PostgreSQL), dan
-- setiap koreksi meninggalkan jejak siapa yang mengubah dan kenapa.
--
-- Karyawan adalah users, bukan tabel master baru: setiap orang yang bisa menekan
-- tombolnya sudah harus punya akun untuk login sama sekali. Presedennya
-- pemakaian.id_pemohon — siapa pun di users boleh jadi subjeknya, divalidasi
-- foreign key saja.

CREATE TABLE presensi (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user BIGINT  NOT NULL REFERENCES users (id),
    -- tanggal adalah tanggal kalender WIB dari jam_masuk, dipotong di Go
    -- (usecase.tanggalPresensi). Tidak dijadikan CHECK terhadap jam_masuk karena
    -- timestamptz::date bergantung pada setelan TimeZone sesi (STABLE, bukan
    -- IMMUTABLE) sehingga tidak boleh muncul di CHECK. Satu-satunya tempat WIB
    -- diputuskan adalah usecase.zonaWIB, dan koreksi jam pun dijaga tetap jatuh
    -- di tanggal ini.
    tanggal    DATE        NOT NULL,
    shift      VARCHAR     NOT NULL,
    jam_masuk  TIMESTAMPTZ NOT NULL,
    jam_pulang TIMESTAMPTZ,
    status     VARCHAR     NOT NULL DEFAULT 'BUKA',

    -- id_unit_kerja adalah SNAPSHOT dari konteks aktif sesi saat menekan tombol
    -- masuk, bukan turunan yang dibaca ulang nanti: grant seseorang bisa
    -- berpindah unit bulan depan, dan rekap bulan lalu tidak boleh ikut
    -- berpindah bersamanya. NULL berarti grantnya global — bacaan yang sama
    -- yang dibawa user_role.id_unit_kerja IS NULL di mana-mana.
    id_unit_kerja BIGINT REFERENCES unit_kerja (id),

    sumber_masuk  VARCHAR NOT NULL DEFAULT 'TOMBOL',
    sumber_pulang VARCHAR,
    -- ip_masuk/ip_pulang belum membuktikan apa pun: ctx.IP() dipakai apa
    -- adanya dan proyek ini tidak punya konfigurasi trusted-proxy di mana pun
    -- — persis peringatan yang sudah ditulis untuk throttling login. Diisi
    -- sekarang supaya berguna begitu setelan itu ada, bukan supaya dipercaya
    -- hari ini.
    ip_masuk  INET,
    ip_pulang INET,

    dikoreksi_oleh BIGINT REFERENCES users (id),
    ts_koreksi     TIMESTAMPTZ,
    alasan_koreksi TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- VARCHAR + CHECK, bukan enum PostgreSQL. Presedennya 000021/000022/000023 yang
-- justru mengganti kosakata enum dengan CHECK: ALTER TYPE ... ADD VALUE tidak
-- bisa dibatalkan, dan shift ketiga (sore, lembur, akhir pekan) adalah persis
-- jenis perubahan yang pantas murah.
ALTER TABLE presensi
    ADD CONSTRAINT presensi_shift_check CHECK (shift IN ('PAGI', 'MALAM')),
    ADD CONSTRAINT presensi_status_check CHECK (status IN ('BUKA', 'SELESAI', 'LUPA_PULANG')),
    ADD CONSTRAINT presensi_sumber_check CHECK (
        sumber_masuk IN ('TOMBOL', 'KOREKSI')
        AND (sumber_pulang IS NULL OR sumber_pulang IN ('TOMBOL', 'KOREKSI'))
    ),
    ADD CONSTRAINT presensi_jam_check CHECK (jam_pulang IS NULL OR jam_pulang > jam_masuk),
    -- Dikoreksi tanpa alasan, atau beralasan tanpa yang mengoreksi: keduanya
    -- baris yang tidak bisa dibaca siapa pun nanti.
    ADD CONSTRAINT presensi_koreksi_check CHECK ((dikoreksi_oleh IS NULL) = (alasan_koreksi IS NULL));

-- Satu orang satu presensi PER SHIFT per hari. Perhatikan shift di kuncinya:
-- tanpa itu orang yang hadir pagi DAN malam tertolak di ketukan keduanya, dan
-- justru hari yang paling bernilai bagi penggajian yang jadi tidak bisa dicatat.
CREATE UNIQUE INDEX presensi_user_tanggal_shift_uidx ON presensi (id_user, tanggal, shift);

-- Partial, dan shift SENGAJA tidak ada di kuncinya: seseorang tidak bisa berada
-- di dua shift sekaligus. Indeks ini melakukan dua hal, persis seperti
-- stok_opname_ruang_terbuka_uidx: menghalangi dua shift terbuka bersamaan pada
-- satu orang, dan membuat "baris mana yang ditutup tombol pulang" punya tepat
-- satu jawaban — tanpanya Pulang harus menebak.
CREATE UNIQUE INDEX presensi_terbuka_uidx ON presensi (id_user) WHERE status = 'BUKA';

-- Pemecah seri unik wajib ikut setiap ORDER BY yang dipasangkan LIMIT/OFFSET,
-- kalau tidak satu baris bisa muncul di dua halaman sementara baris lain tidak
-- pernah keluar.
CREATE INDEX presensi_rekap_idx ON presensi (tanggal DESC, id DESC);
CREATE INDEX presensi_user_idx ON presensi (id_user, tanggal DESC);

CREATE TRIGGER presensi_set_updated_at
    BEFORE UPDATE ON presensi
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
