-- Isu #12 fase 1-2: unit_kerja sebagai master, dan ruang mendapat id_unit_kerja
-- wajib. Token hari ini menjawab satu pertanyaan (siapa); ini yang membuatnya
-- bisa menjawab juga di mana. Ruang tanpa unit adalah ruang yang tidak bisa
-- diputuskan siapa berhak memakainya.
--
-- Wewenang bertempat (user_role.id_unit_kerja) dan konteks aktif per sesi
-- (klaim JWT, POST /auth/switch-context) adalah fase 3-5 dari isu yang sama
-- dan TIDAK ada di migrasi ini. Lihat "Unit kerja and location-bound
-- authority" di CLAUDE.md untuk pemecahan fasenya dan tiga keputusan yang
-- sudah diambil di muka: seri nomor document_counter per unit (implementasi
-- ditunda), periode tetap global, dan mutasi antar unit diperbolehkan.

CREATE TABLE unit_kerja (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode       VARCHAR,
    nama       VARCHAR NOT NULL,
    is_aktif   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT
);

-- Sama seperti setiap tabel master sejak migrasi 000009: unik hanya kalau kode
-- benar-benar diisi, tidak peka huruf besar-kecil, dan kode NULL tidak pernah
-- bentrok dengan NULL lain — indeks unik PostgreSQL tidak membatasi NULL.
CREATE UNIQUE INDEX unit_kerja_kode_lower_uidx ON unit_kerja (lower(kode));
CREATE INDEX unit_kerja_nama_idx ON unit_kerja (nama, id);

-- created_by/updated_by nullable dan diisi NULL sampai pemanggilnya
-- menyertakan actor — pola yang sama dengan seluruh master data lain.
ALTER TABLE unit_kerja
    ADD CONSTRAINT unit_kerja_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT unit_kerja_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;

CREATE TRIGGER unit_kerja_set_updated_at
    BEFORE UPDATE ON unit_kerja
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ruang.id_unit_kerja: ditambah nullable dulu karena ruang sudah ada sejak
-- migrasi 000002 dan baris yang sudah ada belum punya apa pun untuk ditunjuk,
-- dibackfill di bawah, baru dikunci NOT NULL. Backfill dilakukan di sini,
-- bukan diserahkan ke seeder, supaya migrasi ini aman untuk SETIAP jalur
-- upgrade — bukan cuma database yang masih kosong. Sebuah deployment yang
-- sudah punya baris ruang tetap melewati migrasi ini, dan seeder tidak pernah
-- dijamin berjalan sebelum NOT NULL di bawah diterapkan.
ALTER TABLE ruang ADD COLUMN id_unit_kerja BIGINT;

-- Satu unit bawaan, kode 'PUSAT' supaya seeder dan migrasi berikutnya bisa
-- menunjuknya lewat nama, bukan menebak id. Pada database yang masih kosong
-- ini membackfill nol baris (ruang belum diisi; seeder berjalan sesudah
-- seluruh migrasi) dan sekadar meninggalkan unit bawaan untuk ditunjuk
-- 001_ruang.sql.
WITH unit_bawaan AS (
    INSERT INTO unit_kerja (kode, nama) VALUES ('PUSAT', 'Unit Utama')
    RETURNING id
)
UPDATE ruang SET id_unit_kerja = (SELECT id FROM unit_bawaan)
WHERE id_unit_kerja IS NULL;

ALTER TABLE ruang ALTER COLUMN id_unit_kerja SET NOT NULL;

ALTER TABLE ruang
    ADD CONSTRAINT ruang_id_unit_kerja_fkey FOREIGN KEY (id_unit_kerja) REFERENCES unit_kerja (id);

CREATE INDEX ruang_id_unit_kerja_idx ON ruang (id_unit_kerja);
