-- kartu_stok adalah satu-satunya sumber kebenaran stok dan nilai persediaan.
-- Tidak ada kolom stok di tabel master, dan tabel ini append-only (dijaga oleh
-- trigger di migrasi 000004).
--
-- Semua kuantitas disimpan dalam satuan dasar. qty_input/id_satuan_input hanya
-- jejak audit dari apa yang diketik operator.
CREATE TABLE kartu_stok (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_barang          BIGINT          NOT NULL,
    id_ruang           BIGINT          NOT NULL,
    tanggal_transaksi  TIMESTAMPTZ     NOT NULL,
    jenis_transaksi    jenis_transaksi NOT NULL,
    stok_awal          BIGINT          NOT NULL DEFAULT 0,
    stok_masuk         BIGINT          NOT NULL DEFAULT 0,
    stok_keluar        BIGINT          NOT NULL DEFAULT 0,
    stok_akhir         BIGINT          NOT NULL DEFAULT 0,
    qty_input          NUMERIC(18, 4),
    id_satuan_input    BIGINT,
    harga_pokok_satuan NUMERIC(20, 4)  NOT NULL DEFAULT 0,
    nilai_masuk        NUMERIC(20, 2)  NOT NULL DEFAULT 0,
    nilai_keluar       NUMERIC(20, 2)  NOT NULL DEFAULT 0,
    nilai_akhir        NUMERIC(20, 2)  NOT NULL DEFAULT 0,
    ref_table          VARCHAR         NOT NULL,
    ref_id_transaksi   BIGINT          NOT NULL,
    id_kartu_stok_asal BIGINT,
    keterangan         TEXT,
    created_by         BIGINT          NOT NULL,
    created_at         TIMESTAMPTZ     NOT NULL DEFAULT now(),

    CONSTRAINT kartu_stok_stok_masuk_check   CHECK (stok_masuk >= 0),
    CONSTRAINT kartu_stok_stok_keluar_check  CHECK (stok_keluar >= 0),
    -- Satu baris hanya boleh satu arah; campuran membuat saldo mustahil diaudit.
    CONSTRAINT kartu_stok_satu_arah_check    CHECK (NOT (stok_masuk > 0 AND stok_keluar > 0)),
    CONSTRAINT kartu_stok_nilai_masuk_check  CHECK (nilai_masuk >= 0),
    CONSTRAINT kartu_stok_nilai_keluar_check CHECK (nilai_keluar >= 0),
    CONSTRAINT kartu_stok_stok_akhir_check   CHECK (stok_akhir >= 0)
);

-- Saldo berjalan dibaca per (barang, ruang) diurutkan id DESC; index ini yang
-- membuat pembacaan saldo terakhir tetap O(1).
CREATE INDEX kartu_stok_saldo_idx      ON kartu_stok (id_barang, id_ruang, id);
CREATE INDEX kartu_stok_ref_idx        ON kartu_stok (ref_table, ref_id_transaksi);
CREATE INDEX kartu_stok_tanggal_idx    ON kartu_stok (tanggal_transaksi);
CREATE INDEX kartu_stok_asal_idx       ON kartu_stok (id_kartu_stok_asal);

ALTER TABLE kartu_stok
    ADD CONSTRAINT kartu_stok_id_barang_fkey          FOREIGN KEY (id_barang) REFERENCES product (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT kartu_stok_id_ruang_fkey           FOREIGN KEY (id_ruang) REFERENCES ruang (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT kartu_stok_id_satuan_input_fkey    FOREIGN KEY (id_satuan_input) REFERENCES satuan (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT kartu_stok_id_kartu_stok_asal_fkey FOREIGN KEY (id_kartu_stok_asal) REFERENCES kartu_stok (id) DEFERRABLE INITIALLY IMMEDIATE,
    ADD CONSTRAINT kartu_stok_created_by_fkey         FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE;
